spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://118.24.115.208:3306/daival?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
