

# thymeleaf模板配置信息
  thymeleaf:
    prefix: classpath:/templates/
  spring:
    thymeleaf:
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      servlet:
        content-type: text/html
      cache: false
    resources:
      chain:
        strategy:
          content:
            enabled: false
            paths: /**
   # 数据库配置
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/test
      username: root
      password: root

  #服务器配置
  server:
    port: 8080

