spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxxx
    password: xxxxx
    url: jdbc:mysql://localhost:3306/tets?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
